
> clean_mean@1.0.0 testing /Users/markuskuhn/work/projects/Clean-Mean-Stack-With-Login
> concurrently npm:run:node npm:run:angular

[run:angular] 
[run:angular] > clean_mean@1.0.0 run:angular /Users/markuskuhn/work/projects/Clean-Mean-Stack-With-Login
[run:angular] > cd 'application/public/front-end' && nohup ng serve
[run:angular] 
[run:node] 
[run:node] > clean_mean@1.0.0 run:node /Users/markuskuhn/work/projects/Clean-Mean-Stack-With-Login
[run:node] > nohup node server.js
[run:node] 
[run:node] events.js:292
[run:node]       throw er; // Unhandled 'error' event
[run:node]       ^
[run:node] 
[run:node] Error: listen EADDRINUSE: address already in use :::5050
[run:node]     at Server.setupListenHandle [as _listen2] (net.js:1318:16)
[run:node]     at listenInCluster (net.js:1366:12)
[run:node]     at Server.listen (net.js:1452:7)
[run:node]     at Function.listen (/Users/markuskuhn/work/projects/Clean-Mean-Stack-With-Login/node_modules/express/lib/application.js:618:24)
[run:node]     at Object.<anonymous> (/Users/markuskuhn/work/projects/Clean-Mean-Stack-With-Login/server.js:18:5)
[run:node]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[run:node]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[run:node]     at Module.load (internal/modules/cjs/loader.js:928:32)
[run:node]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[run:node]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
[run:node]     at internal/main/run_main_module.js:17:47
[run:node] Emitted 'error' event on Server instance at:
[run:node]     at emitErrorNT (net.js:1345:8)
[run:node]     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
[run:node]   code: 'EADDRINUSE',
[run:node]   errno: -48,
[run:node]   syscall: 'listen',
[run:node]   address: '::',
[run:node]   port: 5050
[run:node] }
[run:node] npm ERR! code ELIFECYCLE
[run:node] npm ERR! errno 1
[run:node] npm ERR! clean_mean@1.0.0 run:node: `nohup node server.js`
npm ERR! Exit status 1
[run:node] npm ERR! 
[run:node] npm ERR! Failed at the clean_mean@1.0.0 run:node script.
[run:node] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[run:node] 
[run:node] npm ERR! A complete log of this run can be found in:
[run:node] npm ERR!     /Users/markuskuhn/.npm/_logs/2021-05-26T09_56_14_738Z-debug.log
[run:node] npm run run:node exited with code 1
[run:angular] ? Port 4200 is already in use.
Would you like to use a different port? (Y/n) [46D[46C